services:
  api:
    user: root
    build:
      context: ./submodules/ScoreHubAPI
      dockerfile: Dockerfile
    container_name: scorehub-api_c
    volumes:
      - ./songs:/app/songs
      - ./songs/tmp:/app/songs/tmp
      - ./scores:/app/scores
      - ./scores/tmp:/app/scores/tmp
    ports: 
      - 5000:5000
    environment:
      ASPNETCORE_URLS: "http://*:5000"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - scorehub-db

  app:
    build:
      context: ./submodules/ScoreHubApp
      dockerfile: Dockerfile
    volumes:
      - ./submodules/ScoreHubApp:/app
    restart: on-failure
    container_name: scorehub-app_c
    ports: 
      - 5173:5173
    depends_on:
      - api      
  
  scorehub-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: scorehub-db_c
    ports: 
      - 5432:5432
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
    volumes:
      - mssql_server:/var/opt/mssql

volumes:
  mssql_server:
  songs:
